name: Deploy Maintenance Page

on:
  push:
    branches:
      - main # Or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Or your preferred runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Take application offline
        run: |
          # Create app_offline.htm file in the web root directory
          echo "Taking application offline for deployment"
          echo '<!DOCTYPE html><html><head><title>Maintenance</title></head><body><h1>Maintenance in progress</h1><p>We are currently updating our application. Please check back soon.</p></body></html>' > /site/wwwroot/app_offline.htm # Replace with your actual path
