# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ssr-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_0d47c9bc2595480b81e7b05157a5a037 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b829f1bbd57d415283764722459f6f60 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0d47c9bc2595480b81e7b05157a5a037 }}/ssr-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ssr-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9a5ac1e177eb456a9a3078dce42296d4 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0d47c9bc2595480b81e7b05157a5a037 }}/ssr-app:${{ github.sha }}'